

trajectory_tracking:
  rho_d2path: 0.2
  rho_d2goal: 0.0
  rho_speed_dev: 50.0
  rho_course_dev: 0.0
  rho_turn_rate: 10.0
  rho_goal: 0.0
  goal_radius: 50.0
colreg:
  alpha_cr: [0.02, 0.001]
  y_0_cr: 300.0
  alpha_ho: [0.01, 0.02]
  x_0_ho: 300.0
  alpha_ot: [0.002, 0.001]
  x_0_ot: 150.0
  y_0_ot: 10.0
  d_attenuation: 375.0
  w_colregs: [200.0, 200.0, 200.0]
  colregs_handler:
    theta_critical_ot: 45.0  # contact angle threshold for OT situation
    theta_critical_ho: 13.0 # contact and bearing angle threshold for HO situation
    theta_critical_cr: -13.0   # contact and bearing angle threshold for CR situation
    theta_ot_min: 112.5  # minimum bearing angle for OT situation
    theta_ot_max: 247.5  # maximum bearing angle for OT situation
    d_critical_so: 100.0 # critical distance threshold where stand-on duties are aborted
    d_activation: 1000.0  # distance threshold for activation of COLREGS handler
    t_cpa_entry: 120.0  # time to CPA threshold for entry into COLREGS situation
    d_cpa_entry: 100.0  # distance to CPA threshold for entry into COLREGS situation
readily_apparent_maneuvering:
  alpha_app_course: [40.0, 0.0008]
  alpha_app_speed: [15.0, 0.001]
  K_app_course: 50.0
  K_app_speed: 50.0
  r_max: 8.0
  a_max: 0.3
collision_avoidance:
  rho_colav: 10000.0
  r_safe: 15.0
anti_grounding:
  reference_traj_bbox_buffer: 200.0
  rho_anti_grounding: 10000.0
  r_safe: 5.0
dnn_parameter_provider:
  disable: False
  rho_solver_time: 0.0
  rho_qp_failure: 10000.0
  rho_high_app_params: 0.0
  rho_safety_param: 5.0
  rho_diff_colreg_weights: 0.0
  rho_hitting_bounds: 5.0
  rho_low_Q_p: 0.0
action_chatter:
  rho_chatter: [0.5, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.5]
