rl:
  learning_rate: 0.1

los:
  pass_angle_threshold: 80.0
  R_a: 25.0
  K_p: 0.024
  K_i: 0.0
  e_int_max: 101.0

ktp:
  epsilon: 0.00001

mpc:
  params:
    rate: 0.2
    reference_traj_bbox_buffer: 200.0
    T: 35.0
    dt: 0.5
    Q: [20.0, 20.0, 0.1, 0.1, 0.1, 0.1]
    R: [0.00001, 0.00001]
    w_L2: 0.0
    w_L1: 1000.0
    d_safe_so: 5.0
    d_safe_do: 10.0
    gamma: 1.0
    so_constr_type: "PARAMETRICSURFACE"
    max_num_so_constr: 3
    max_num_do_constr: 0 # per shooting node in the mpc
    path_following: False
    debug: True
  enable_acados: True
  solver_options:
    casadi:
      solver_type: "ipopt"
      solver_tol: 0.0001
      print_level: 5
      print_time: 0
      mu_target: 0.0001
      mu_init: 0.0001
      acceptable_tol: 0.0001
      acceptable_obj_change_tol: 0.0001
      max_iter: 400
      warm_start_init_point: "no"
      verbose: False
      jit: False
      jit_flags: ["-O3"]
      compiler: "shell"
      expand_mx_funcs_to_sx: False
    acados:
      nlp_solver_type: "SQP"
      nlp_solver_max_iter: 300
      nlp_solver_tol_stat: 0.01
      nlp_solver_tol_eq: 0.0001
      nlp_solver_tol_ineq: 0.0001
      nlp_solver_tol_comp: 0.0001
      nlp_solver_ext_qp_res: 1
      qp_solver_type: "PARTIAL_CONDENSING_HPIPM" #"PARTIAL_CONDENSING_HPIPM"  "FULL_CONDENSING_QPOASES"
      qp_solver_iter_max: 100
      qp_solver_warm_start: 1
      qp_solver_tol_stat: 0.01
      qp_solver_tol_eq: 0.001
      qp_solver_tol_ineq: 0.001
      qp_solver_tol_comp: 0.001
      hessian_approx_type: "EXACT"
      globalization: "MERIT_BACKTRACKING"
      regularize_method: "PROJECT"
      levenberg_marquardt: 0.01
      print_level: 1
      ext_fun_compile_flags: "-O0" # "-march=native -flto -fomit-frame-pointer -O0"