rl:
  learning_rate: 0.1

los:
  pass_angle_threshold: 80.0
  R_a: 25.0
  K_p: 0.024
  K_i: 0.0
  e_int_max: 101.0
ktp:
  epsilon: 0.00001

mpc:
  params:
    rate: 0.1
    reference_traj_bbox_buffer: 300.0
    T: 25.0
    dt: 0.5
    Q: [10.0, 10.0] #, 0.1, 1.0, 1.0, 1.0]
    d_safe_so: 5.0
    d_safe_do: 10.0
    gamma: 1.0
    so_constr_type: "PARAMETRICSURFACE"
    max_num_so_constr: 15
    max_num_do_constr: 0 # per shooting node in the mpc
    path_following: True
    debug: True
  enable_acados: False
  solver_options:
    casadi:
      solver_type: "ipopt"
      solver_tol: 0.000001
      print_level: 0
      print_time: 0
      mu_target: 0.000001
      mu_init: 0.000001
      acceptable_tol: 0.000001
      acceptable_obj_change_tol: 0.000001
      max_iter: 500
      warm_start_init_point: "yes"
      verbose: False
      jit: False
      jit_flags: ["-O3"]
      compiler: "shell"
      expand_mx_funcs_to_sx: False
    acados:
      nlp_solver_type: "SQP"
      nlp_solver_max_iter: 300
      nlp_solver_tol_stat: 0.000001
      nlp_solver_tol_eq: 0.000001
      nlp_solver_tol_ineq: 0.000001
      nlp_solver_tol_comp: 0.000001
      nlp_solver_ext_qp_res: 0
      qp_solver_type: "PARTIAL_CONDENSING_HPIPM"
      qp_solver_iter_max: 100
      qp_solver_warm_start: 1
      hessian_approx_type: "EXACT"
      globalization: "MERIT_BACKTRACKING"
      levenberg_marquardt: 0.0
      print_level: 0