rl:
  learning_rate: 0.1

rrt:
  max_nodes: 1000
  max_iter: 10000
  iter_between_direct_goal_growth: 100
  min_node_dist: 5.0
  goal_radius: 100.0
  step_size: 0.5
  max_steering_time: 20.0
  steering_acceptance_radius: 5.0
  max_node_dist: 300.0
  gamma: 1000.0

mpc:
  T: 100.0
  dt: 0.5
  Q: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
  R: [1.0, 1.0, 1.0]
  gamma: 0.5