rl:
  learning_rate: 0.1

rrt:
  max_nodes: 4000
  max_iter: 10000
  iter_between_direct_goal_growth: 200
  min_node_dist: 30.0
  goal_radius: 300.0
  step_size: 0.5
  max_steering_time: 35.0
  steering_acceptance_radius: 5.0
  max_nn_node_dist: 100.0
  gamma: 1200.0

mpc:
  params:
    reference_traj_bbox_buffer: 500.0
    T: 1.0
    dt: 0.5
    Q: [100.0, 100.0, 1.0, 1.0, 0.05, 0.01]
    d_safe_so: 5.0
    d_safe_do: 10.0
    gamma: 0.99
    so_constr_type: "SURFACE_APPROX"
    path_following: False
  enable_acados: False
  solver_options:
    casadi:
      solver_type: "ipopt"
      solver_tol: 0.000001
      print_level: 3
      print_time: 0
      mu_target: 0.000001
      mu_init: 0.000001
      acceptable_tol: 0.000001
      acceptable_obj_change_tol: 0.000001
      max_iter: 100
    acados:
      nlp_solver_type: "SQP"
      nlp_solver_max_iter: 300
      nlp_solver_tol_stat: 0.000001
      nlp_solver_tol_eq: 0.000001
      nlp_solver_tol_ineq: 0.000001
      nlp_solver_tol_comp: 0.000001
      nlp_solver_ext_qp_res: 0
      qp_solver_type: "FULL_CONDENSING_QPOASES"
      qp_solver_iter_max: 100
      qp_solver_warm_start: 1
      hessian_approx_type: "EXACT"
      globalization: "MERIT_BACKTRACKING"
      levenberg_marquardt: 0.0
      print_level: 0