rl:
  learning_rate: 0.1

rrt:
  max_nodes: 4000
  max_iter: 20000
  iter_between_direct_goal_growth: 1000
  min_node_dist: 10.0
  goal_radius: 500.0
  step_size: 0.5
  max_steering_time: 30.0
  steering_acceptance_radius: 5.0
  max_nn_node_dist: 700.0
  gamma: 3000.0

mpc:
  T: 100.0
  dt: 0.5
  Q: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
  R: [1.0, 1.0, 1.0]
  gamma: 0.5