rl:
  learning_rate: 0.1

pq_rrt:
  max_nodes: 2500
  max_iter: 5000
  iter_between_direct_goal_growth: 500
  min_node_dist: 30.0
  goal_radius: 300.0
  step_size: 0.5
  max_steering_time: 25.0
  steering_acceptance_radius: 5.0
  max_nn_node_dist: 150.0
  gamma: 1200.0
  max_sample_adjustments: 80
  lambda_sample_adjustment: 0.5
  safe_distance: 0.1
  max_ancestry_level: 4

# i_rrt:
#   max_nodes: 2500
#   max_iter: 5000
#   iter_between_direct_goal_growth: 200
#   min_node_dist: 30.0
#   goal_radius: 300.0
#   step_size: 0.5
#   max_steering_time: 15.0
#   steering_acceptance_radius: 5.0
#   max_nn_node_dist: 150.0
#   gamma: 1200.0

mpc:
  params:
    rate: 0.2
    reference_traj_bbox_buffer: 200.0
    T: 40.0
    dt: 0.5
    Q: [0.01, 0.01, 0.01, 2.5, 0.5, 0.03]
    R: [0.0001, 0.001]
    w_L2: 0.0
    w_L1: 1350.0
    d_safe_so: 5.0
    d_safe_do: 10.0
    gamma: 1.0
    so_constr_type: "PARAMETRICSURFACE"
    max_num_so_constr: 11
    max_num_do_constr: 0 # per shooting node in the mpc
    path_following: False
    debug: True
  enable_acados: True
  solver_options:
    casadi:
      solver_type: "ipopt"
      solver_tol: 0.001
      print_level: 5
      print_time: 0
      mu_target: 0.0001
      mu_init: 0.0001
      acceptable_tol: 0.001
      acceptable_obj_change_tol: 0.001
      max_iter: 200
      warm_start_init_point: "yes"
      verbose: False
      jit: False
      jit_flags: ["-O3"]
      compiler: "shell"
      expand_mx_funcs_to_sx: False
    acados:
      nlp_solver_type: "SQP"
      nlp_solver_max_iter: 50
      nlp_solver_tol_stat: 0.01
      nlp_solver_tol_eq: 0.0001
      nlp_solver_tol_ineq: 0.001
      nlp_solver_tol_comp: 0.001
      nlp_solver_ext_qp_res: 0
      qp_solver_type: "PARTIAL_CONDENSING_HPIPM" #"PARTIAL_CONDENSING_HPIPM"  "FULL_CONDENSING_QPOASES"
      qp_solver_iter_max: 100
      qp_solver_warm_start: 1
      qp_solver_tol_stat: 0.01
      qp_solver_tol_eq: 0.001
      qp_solver_tol_ineq: 0.001
      qp_solver_tol_comp: 0.001
      hessian_approx_type: "EXACT"
      globalization: "MERIT_BACKTRACKING"
      regularize_method: "PROJECT"
      levenberg_marquardt: 0.001
      print_level: 0
      ext_fun_compile_flags: "-O0" # "-march=native -flto -fomit-frame-pointer -O0"