verbose: True
manual_episode_accept: True
#scenario_files: ["head_on.yaml", "crossing_give_way.yaml", "crossing_stand_on.yaml", "overtaking.yaml", "overtaken.yaml"]
#scenario_files: ["rl_scenario.yaml"]
scenario_files: ["head_on_sbmpc.yaml"]
#scenario_files: ["ais_scenario1.yaml"]
#scenario_files: ["simple_planning_example.yaml"]
#scenario_files: ["saved/aalesund_random2_18012023_13_48_46.yaml"]
#scenario_files: ["saved/aalesund_random_20012023_13_00_55.yaml"]
#scenario_folder: "imazu_cases"
ho_bearing_range: [-3.0, 3.0]
ho_heading_range: [-5.0, 5.0]
ot_bearing_range: [-20.0, 20.0]
ot_heading_range: [-15.0, 15.0]
cr_bearing_range: [10.1, 90.5]
cr_heading_range: [-10.0, 10.0]
dist_between_ships_range: [300.0, 600.0] #[500.0, 800.0] # [300.0, 800.0] # [500.0, 800.0]
csog_state_perturbation_covariance: [100.0, 100.0, 0.5, 2.0] # for state [x, y, U, chi], with last entry in degrees
t_cpa_threshold: 1000.0
d_cpa_threshold: 150.0

behavior_generator:
  ownship_method: "RRTStar" # "ConstantSpeedRandomWaypoints" # "VaryingSpeedRandomWaypoints"
  target_ship_method: "ConstantSpeedRandomWaypoints" # "RRT" # "PQRRTStar"

  n_wps_range: [2, 4]
  speed_plan_variation_range: [-1.0, 1.0]
  waypoint_dist_range: [300.0, 1000.0]
  waypoint_ang_range: [-90.0, 90.0]
  hazard_buffer: 0.0

  # Can use 3 different RRT-algorithms for behavior generation: PQ-RRT*, RRT* and RRT:
  pqrrtstar:
    params:
      max_nodes: 3000
      max_iter: 25000
      max_time: 5.0
      iter_between_direct_goal_growth: 500000
      min_node_dist: 5.0
      goal_radius: 50.0
      step_size: 0.5
      min_steering_time: 1.0
      max_steering_time: 30.0
      steering_acceptance_radius: 10.0
      gamma: 2000.0
      max_sample_adjustments: 0
      lambda_sample_adjustment: 4.0
      safe_distance: 0.1
      max_ancestry_level: 1
    model:
      csog:
        draft: 0.5
        length: 15.0
        width: 4.0
        T_chi: 6.0
        T_U: 6.0
        r_max: 10.0
        U_min: 0.0
        U_max: 10.0
    los:
      pass_angle_threshold: 90.0
      R_a: 25.0
      K_p: 0.035
      K_i: 0.0
      max_cross_track_error_int: 30.0
  rrtstar:
    params:
      max_nodes: 3000
      max_iter: 25000
      max_time: 5.0
      iter_between_direct_goal_growth: 500000
      min_node_dist: 5.0
      goal_radius: 50.0
      step_size: 0.5
      min_steering_time: 1.0
      max_steering_time: 30.0
      steering_acceptance_radius: 10.0
      gamma: 2000.0
    model:
      csog:
        draft: 0.5
        length: 15.0
        width: 4.0
        T_chi: 6.0
        T_U: 6.0
        r_max: 10.0
        U_min: 0.0
        U_max: 10.0
    los:
      pass_angle_threshold: 90.0
      R_a: 25.0
      K_p: 0.035
      K_i: 0.0
      max_cross_track_error_int: 30.0

  rrt:
    params:
      max_nodes: 3000
      max_iter: 25000
      max_time: 5.0
      iter_between_direct_goal_growth: 500000
      goal_radius: 50.0
      step_size: 0.5
      min_steering_time: 1.0
      max_steering_time: 30.0
      steering_acceptance_radius: 10.0
    model:
      csog:
        draft: 0.5
        length: 15.0
        width: 4.0
        T_chi: 6.0
        T_U: 6.0
        r_max: 10.0
        U_min: 0.0
        U_max: 10.0
    los:
      pass_angle_threshold: 90.0
      R_a: 25.0
      K_p: 0.035
      K_i: 0.0
      max_cross_track_error_int: 30.0


