
[rust]
debug = true
debuginfo-level = 2
backtrace = true

[term]
verbose = false
color = "auto"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]